stages:
  - build
build-code-job:
  stage: build
  image: node:18-buster
  variables :
    $PRIVATE_SSH_KEY: $PRIVATE_SSH_KEY
  script:
  - echo "Building Docker image..."
  - echo "Docker image built successfully."
  - echo "'$PRIVATE_SSH_KEY'"