stages:
  # - build
  - merge
# build-code-job:
#   stage: build
#   image: node:18-buster
#   script:
#   - echo "Building Docker image..."
#   - echo "Docker image built successfully."
merge-main-job:
  stage: merge
  image: node:18-buster
  script:
    # TODO: merge feature branch into main
    - git config --global user.email "yayoub@st.noorderpoort.nl"
    - git config --global user.name "yamen22-dev"
    - git fetch
    - git checkout main
    - git merge origin/feature
    - ssh-add -K ~/.ssh/$PRIVATE_SSH_KEY
    - git push -o ci-skip git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git HEAD:main
  only:
    - feature
