stages:
  - build
  - merge
build-code-job:
  stage: build
  image: node:18-buster
  script:
  - echo "Building Docker image..."
  - echo "Docker image built successfully."
merge-main-job:
  stage: merge
  image: node:18-buster
  script:
    # TODO: merge feature branch into main
    - git fetch
    - git checkout main
    - git merge --no-ff origin/feature
    - git push origin main 
  only:
    - feature
