stages:
  - test

variables:
  GLOBAL_VARIABLE: "I am a global variable"

run_job:
  stage: test
  script:
    - echo "Hello, this is a hardcoded string!"

    - echo "Global Variable:GLOBAL_VARIABLE"

    - LOCAL_VARIABLE="I am a local variable"

    - echo "Local Variable:$LOCAL_VARIABLE"

    - echo "Job Name:$CI_JOB_NAME"

  tags:
    - shared
