stages:
  # - build
  - merge
# build-code-job:
#   stage: build
#   image: node:18-buster
#   script:
#   - echo "Building Docker image..."
#   - echo "Docker image built successfully."
merge-main-job:
  stage: merge
  image: node:18-buster
  script:
    # TODO: merge feature branch into main
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    - ssh-add <(echo "$PRIVATE_SSH_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git config --global user.email "yayoub@st.noorderpoort.nl"
    - git config --global user.name "yamen22-dev"
    - git fetch
    - git checkout main
    - git merge origin/feature
    - git push -o ci-skip git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git HEAD:main
  only:
    - feature
