stages:
  # - build
  - merge
# build-code-job:
#   stage: build
#   image: node:18-buster
#   script:
#   - echo "Building Docker image..."
#   - echo "Docker image built successfully."
merge-main-job:
  stage: merge
  image: node:18-buster
  script:
    # TODO: merge feature branch into main
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    - echo "$PRIVATE_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git config --global user.email "yayoub@st.noorderpoort.nl"
    - git config --global user.name "yamen22-dev"
    - git remote set-url origin git@gitlab.com:ci-cd4341350/cdproject.git
    - git fetch
    - git checkout origin/main
    - git pull origin main
    - git merge origin/feature
    - git commit -m "Merge feature into main"
    - git push origin main
    # - git merge --allow-unrelated-histories origin/main