stages:
  - build
  - deploy
build-code-job:
  stage: build
  image: node:18-buster
  script:
  - echo "Building Docker image..."
  - echo "Docker image built successfully."
  - echo "$PRIVATE_SSH_KEY"
build-second-job:
  stage: build
  script:
  - echo "Ik ben bij second build job."
merge-main-job:
  stage: deploy
  image: node:18-buster
  script:
    # TODO: merge feature branch into main
    - git checkout main
    - git merge feature
    - git push origin main 